name: Deploy FastAPI Worker (Cloudflare)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (for Wrangler)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Show tool versions
        run: |
          node --version
          npm --version
          uv --version

      - name: Install Wrangler CLI
        run: npm i -g wrangler@latest

      - name: Deploy FastAPI worker with pywrangler
        env:
          # Provide both env var names for broader compatibility
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          cd 03-fastapi
          # Deploy using pywrangler to vendor Python deps, then publish via Wrangler
          # Do not pass a --yes flag: Wrangler doesn't accept --yes and it would error.
          uv run pywrangler deploy
      - name: Post-deploy smoke tests
        run: |
          URL="https://api.risingtonklaman.xyz"
          # check root
          status=$(curl -s -o /dev/null -w "%{http_code}" $URL/)
          if [ "$status" -ne 200 ]; then echo "Root not healthy: $status" && exit 1; fi
          # check health
          status=$(curl -s -o /dev/null -w "%{http_code}" $URL/health)
          if [ "$status" -ne 200 ]; then echo "Health not healthy: $status" && exit 1; fi
          # check hi endpoint
          out=$(curl -sS "$URL/hi/testuser" || true)
          echo "$out" | grep -q "Hello" || (echo "hi endpoint failed: $out" && exit 1)